version: '3'

services:
  app:
    build: .
    volumes:
      - ..:/go/src/app:cached
    ports:
      - 8080:8080
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DSN: root:password@tcp(db:3306)/dev?parseTime=true
    tty: true

  db:
    image: mysql:8.0-oracle
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    tty: true
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - '3306:3306'